sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ARGS="--ansi --no-interaction --no-scripts --no-suggest --prefer-dist"

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
        - CS_CHECK=true
    - php: 7
    - php: 7.1
    - php: 7.2
    - php: nightly
    - php: hhvm
  allow_failures:
    - php: nightly
    - php: hhvm

before_install:
  - composer self-update

install:
  - travis_retry composer install --ansi --no-interaction --no-scripts --no-suggest --prefer-dist

script:
  - composer test
  - if [[ $CS_CHECK == 'true' ]]; then composer cs ; fi

notifications:
  email: false
